name: Sync Repository

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Destination Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Add Source Repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote add source https://github.com/praveensri2018/sivanyaAPI.git
          git fetch source
          git merge source/main --allow-unrelated-histories -m "Auto-sync from source"
          git push origin main
